apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: spark
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: "Default project for demo applications"

  # Source repositories that applications within this project can pull from
  sourceRepos:
  - "https://github.com/lapeyus/argocd-example-apps"
  - "*"
  # Destinations that applications within this project can deploy to
  destinations:
  - namespace: "guestbook"
    server: "https://kubernetes.default.svc"
  - namespace: "default"
    server: "https://kubernetes.default.svc"
  # Cluster-scoped resources that may be created by applications in this project
  clusterResourceWhitelist:
  - group: ""
    kind: "Namespace"
  # Namespace-scoped resources that may be created by applications in this project
  namespaceResourceWhitelist:
  - group: ""
    kind: "Service"
  - group: ""
    kind: "ServiceAccount"
  - group: ""
    kind: "ConfigMap"
  - group: ""
    kind: "Secret"
  - group: "apps"
    kind: "Deployment"
  - group: "apps"
    kind: "ReplicaSet"
  - group: "extensions"
    kind: "Ingress"
  - group: "networking.k8s.io"
    kind: "Ingress"
  # Roles that provide fine-grained access control within this project
  roles:
  - name: admin
    description: "Admin access to the project"
    policies:
    - p, proj:spark:admin, applications, *, spark/*, allow
    - p, proj:spark:admin, repositories, *, *, allow
    groups:
    - argocd-admins
